# Site settings
title: Ansh Sarda
description: The personal site of Ansh Sarda.

# User settings
username: ansh sarda
email: anshsarda@outlook.com

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src', 'node_modules']

collections:
  musings:
    output: true
    permalink: /musings/:path/

